# Generated by Django 3.2.5 on 2021-08-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=30, verbose_name='نام گروه')),
                ('description', models.TextField(max_length=100, verbose_name='توضیحات گروه')),
            ],
        ),
    ]
